---
abstract: 'Extremely fast HTML escape'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Devel::PPPort: 3.20
  ExtUtils::CBuilder: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.20
  Module::Build: 0.4003
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Escape
no_index:
  directory:
    - inc
provides:
  HTML::Escape:
    file: lib/HTML/Escape.pm
    version: 1.05
  HTML::Escape::PurePerl:
    file: lib/HTML/Escape/PurePerl.pm
    version: 0
requires:
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.008008
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
